# Generated by Django 4.1.7 on 2023-03-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_date',
            field=models.DateTimeField(default=None),
        ),
    ]
