# Generated by Django 4.1.7 on 2023-03-24 19:31

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_trip_trip_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_date',
            field=models.DateTimeField(default=None, validators=[django.core.validators.MinValueValidator(datetime.datetime.now)]),
        ),
    ]
