# Generated by Django 4.1.7 on 2023-03-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0004_trip_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_date',
            field=models.DateTimeField(default=None),
        ),
    ]
