# Generated by Django 4.1.7 on 2023-03-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0006_trip_seats_avail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='seats_avail',
            field=models.IntegerField(default=1),
        ),
    ]
