# Generated by Django 4.1.7 on 2023-03-25 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0007_alter_trip_seats_avail'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_date',
            field=models.DateTimeField(verbose_name=datetime.datetime.now),
        ),
    ]
