# Generated by Django 4.1.7 on 2023-03-25 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0010_deletedtrips'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeletedTrips',
            new_name='DeletedTrip',
        ),
    ]
