# Generated by Django 4.1.7 on 2023-03-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0011_rename_deletedtrips_deletedtrip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-date_added']},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-date_added']},
        ),
        migrations.AddField(
            model_name='car',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
