# Generated by Django 4.1.7 on 2023-04-11 17:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trip", "0013_userprofile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trip",
            old_name="driver",
            new_name="user",
        ),
    ]
